// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRYKY9UYzxJhif5eZwzdQnwulCflDhrw',
    appId: '1:309692478577:web:842220b244e4e1016e97d0',
    messagingSenderId: '309692478577',
    projectId: 'mynotes0207',
    authDomain: 'mynotes0207.firebaseapp.com',
    storageBucket: 'mynotes0207.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOn4WnnkJA1Ta65skSoNGseDKCXu182P0',
    appId: '1:309692478577:android:c476a1cea53baf486e97d0',
    messagingSenderId: '309692478577',
    projectId: 'mynotes0207',
    storageBucket: 'mynotes0207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPpLe943VuITMRa9XgsCpgtfqj1h126-o',
    appId: '1:309692478577:ios:a948b02ceea62d3a6e97d0',
    messagingSenderId: '309692478577',
    projectId: 'mynotes0207',
    storageBucket: 'mynotes0207.firebasestorage.app',
    iosBundleId: 'com.aonekart.mynotes',
  );

}